import { useState } from 'react'
import { useApp } from '../context/AppContext'

export default function GitPage() {
  const { history, toast } = useApp()
  const [repo, setRepo] = useState('')
  const [token, setToken] = useState('')
  const [branch, setBranch] = useState('main')
  const [commitMsg, setCommitMsg] = useState('feat: initial project generated by ProjectForge')
  const [selectedIdx, setSelectedIdx] = useState('')
  const [pushing, setPushing] = useState(false)
  const [log, setLog] = useState('')

  const addLog = (msg) => setLog(prev => prev + msg + '\n')

  const push = async () => {
    if (!repo.trim()) { toast('Enter a GitHub repo URL', 'error'); return }
    if (!token.trim()) { toast('Enter your GitHub Personal Access Token', 'error'); return }
    if (selectedIdx === '') { toast('Select a project to push', 'error'); return }

    const project = history[parseInt(selectedIdx)]
    if (!project) { toast('Project not found', 'error'); return }

    setPushing(true)
    setLog('')

    try {
      // Parse owner/repo from URL
      const repoMatch = repo.match(/github\.com[/:]([^/]+)\/([^/.\s]+)/)
      if (!repoMatch) throw new Error('Invalid GitHub URL. Use: https://github.com/owner/repo')

      const [, owner, repoName] = repoMatch
      const apiBase = `https://api.github.com/repos/${owner}/${repoName}`
      const headers = {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'Content-Type': 'application/json'
      }

      addLog(`→ Connecting to github.com/${owner}/${repoName}…`)

      // Get or create branch SHA
      addLog(`→ Fetching branch ${branch}…`)
      let baseSha = null
      try {
        const branchRes = await fetch(`${apiBase}/git/refs/heads/${branch}`, { headers })
        if (branchRes.ok) {
          const branchData = await branchRes.json()
          baseSha = branchData.object.sha
          addLog(`→ Branch found: ${baseSha.slice(0, 7)}`)
        } else {
          // Try default branch
          const repoRes = await fetch(apiBase, { headers })
          if (!repoRes.ok) throw new Error(`Repo not accessible: ${repoRes.status}`)
          const repoData = await repoRes.json()
          const defBranch = repoData.default_branch || 'main'
          const defRes = await fetch(`${apiBase}/git/refs/heads/${defBranch}`, { headers })
          if (defRes.ok) {
            const defData = await defRes.json()
            baseSha = defData.object.sha
            addLog(`→ Using default branch ${defBranch}: ${baseSha.slice(0, 7)}`)
          }
        }
      } catch (e) {
        if (!e.message.includes('not accessible')) addLog(`⚠ Could not fetch branch (empty repo?): ${e.message}`)
      }

      // Build files
      addLog(`→ Preparing ${project.folders?.reduce((a, f) => a + (f.files?.length || 0), 0)} files…`)
      const files = []
      for (const folder of project.folders || []) {
        for (const file of folder.files || []) {
          files.push({ path: `${folder.dir || ''}${file.name}`, content: file.code || '' })
        }
      }

      // Create blobs
      addLog(`→ Uploading blobs…`)
      const treeItems = []
      for (const file of files) {
        const blobRes = await fetch(`${apiBase}/git/blobs`, {
          method: 'POST', headers,
          body: JSON.stringify({ content: btoa(unescape(encodeURIComponent(file.content))), encoding: 'base64' })
        })
        if (!blobRes.ok) throw new Error(`Blob upload failed for ${file.path}: ${blobRes.status}`)
        const blob = await blobRes.json()
        treeItems.push({ path: file.path, mode: '100644', type: 'blob', sha: blob.sha })
      }
      addLog(`→ ${treeItems.length} blobs uploaded`)

      // Create tree
      addLog(`→ Creating tree…`)
      const treePayload = baseSha ? { base_tree: baseSha, tree: treeItems } : { tree: treeItems }
      const treeRes = await fetch(`${apiBase}/git/trees`, {
        method: 'POST', headers, body: JSON.stringify(treePayload)
      })
      if (!treeRes.ok) throw new Error(`Tree creation failed: ${treeRes.status}`)
      const treeData = await treeRes.json()

      // Create commit
      addLog(`→ Creating commit…`)
      const commitPayload = {
        message: commitMsg,
        tree: treeData.sha,
        ...(baseSha ? { parents: [baseSha] } : {})
      }
      const commitRes = await fetch(`${apiBase}/git/commits`, {
        method: 'POST', headers, body: JSON.stringify(commitPayload)
      })
      if (!commitRes.ok) throw new Error(`Commit failed: ${commitRes.status}`)
      const commitData = await commitRes.json()
      addLog(`→ Commit: ${commitData.sha.slice(0, 7)}`)

      // Update or create ref
      addLog(`→ Updating ref heads/${branch}…`)
      const refUrl = `${apiBase}/git/refs/heads/${branch}`
      const checkRef = await fetch(refUrl, { headers })
      let refRes
      if (checkRef.ok) {
        refRes = await fetch(refUrl, {
          method: 'PATCH', headers,
          body: JSON.stringify({ sha: commitData.sha, force: false })
        })
      } else {
        refRes = await fetch(`${apiBase}/git/refs`, {
          method: 'POST', headers,
          body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: commitData.sha })
        })
      }
      if (!refRes.ok) throw new Error(`Ref update failed: ${refRes.status}`)

      addLog(`\n✅ Successfully pushed ${project.projectName} to ${owner}/${repoName}@${branch}`)
      addLog(`🔗 https://github.com/${owner}/${repoName}/tree/${branch}`)
      toast('Pushed to GitHub! ✓', 'success')
    } catch (e) {
      addLog(`\n❌ Error: ${e.message}`)
      toast('Push failed: ' + e.message, 'error')
    } finally {
      setPushing(false)
    }
  }

  return (
    <div className="animate-fade-in-up">
      <div className="page-header">
        <div className="page-eyebrow">GitHub Integration</div>
        <h1 className="page-title">Push to Git</h1>
        <p className="page-subtitle">Push any generated project directly to a GitHub repository using the API.</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))', gap: 24 }}>
        <div className="card">
          <div className="card-header">
            <div className="card-title">🐙 GitHub Configuration</div>
          </div>
          <div className="card-body">
            <div className="form-group">
              <label className="form-label">Select Project <span className="required">*</span></label>
              <select className="form-select" value={selectedIdx} onChange={e => setSelectedIdx(e.target.value)}>
                <option value="">— Choose a project —</option>
                {history.map((p, i) => (
                  <option key={i} value={i}>{p.projectName} ({p.stack?.split(' ')[0]})</option>
                ))}
              </select>
              {history.length === 0 && (
                <p className="text-xs text-muted" style={{ marginTop: 6 }}>Generate a project first to push it here</p>
              )}
            </div>

            <div className="form-group">
              <label className="form-label">GitHub Repo URL <span className="required">*</span></label>
              <input
                className="form-input"
                value={repo}
                onChange={e => setRepo(e.target.value)}
                placeholder="https://github.com/username/my-repo"
              />
            </div>

            <div className="form-group">
              <label className="form-label">Personal Access Token <span className="required">*</span></label>
              <input
                className="form-input"
                type="password"
                value={token}
                onChange={e => setToken(e.target.value)}
                placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
              />
              <p className="text-xs text-muted" style={{ marginTop: 6 }}>
                Needs <code style={{ color: 'var(--accent-electric)' }}>repo</code> scope.{' '}
                <a href="https://github.com/settings/tokens/new" target="_blank" rel="noopener noreferrer"
                  style={{ color: 'var(--accent-electric)' }}>Create token →</a>
              </p>
            </div>

            <div className="form-row">
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Branch</label>
                <input className="form-input" value={branch} onChange={e => setBranch(e.target.value)} placeholder="main" />
              </div>
            </div>

            <div className="form-group" style={{ marginTop: 20 }}>
              <label className="form-label">Commit Message</label>
              <input className="form-input" value={commitMsg} onChange={e => setCommitMsg(e.target.value)} />
            </div>

            <button className="btn btn-primary w-full" style={{ marginTop: 8 }} onClick={push} disabled={pushing}>
              {pushing ? <><div className="spinner" /> Pushing…</> : '🚀 Push to GitHub'}
            </button>
          </div>
        </div>

        <div className="git-panel">
          <div className="git-panel-header">
            <span>🖥</span>
            <span className="git-panel-title">Git Output</span>
          </div>
          <div className="git-panel-body">
            <div className="git-log">
              {log || '# Waiting for push operation…\n# Output will appear here\n'}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
